"""Create isolated, inactive provider-adapter candidates for review."""

from __future__ import annotations

import re
from dataclasses import dataclass
from pathlib import Path

from tarel.providers.contracts import ProviderFailure

_PROVIDER_NAME = re.compile(r"^[a-z][a-z0-9_-]*$")


@dataclass(frozen=True, slots=True)
class ProviderScaffoldResult:
    name: str
    path: Path


def scaffold_provider(name: str, *, output: Path | None = None) -> ProviderScaffoldResult:
    if not _PROVIDER_NAME.fullmatch(name):
        raise ProviderFailure(
            "invalid_provider_name",
            "Provider adapter names must start with a lowercase letter and contain only "
            "lowercase letters, numbers, underscores, or hyphens.",
        )
    target = (
        output
        or Path.cwd() / ".tarel" / "providers" / name
    ).expanduser().resolve()
    if target.exists():
        raise ProviderFailure("target_exists", f"Scaffold target already exists: {target}")
    module_name = name.replace("-", "_")
    files = _scaffold_files(name, module_name)
    try:
        for relative, content in files.items():
            path = target / relative
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding="utf-8")
    except OSError as exc:
        raise ProviderFailure(
            "scaffold_failed",
            f"Could not create provider scaffold: {target}",
        ) from exc
    return ProviderScaffoldResult(name, target)


def _scaffold_files(name: str, module_name: str) -> dict[Path, str]:
    return {
        Path("PROVIDER_TASK.md"): _task_template(name),
        Path("README.md"): _readme_template(name),
        Path("pyproject.toml"): _pyproject_template(name, module_name),
        Path("src") / module_name / "__init__.py": "",
        Path("src") / module_name / "provider.py": _provider_template(name),
        Path("references") / "protocol.md": _protocol_reference_template(name),
    }


def _pyproject_template(name: str, module_name: str) -> str:
    return f'''[build-system]
requires = ["hatchling>=1.27"]
build-backend = "hatchling.build"

[project]
name = "tarel-provider-{name}"
version = "0.0.1"
requires-python = ">=3.11"
dependencies = ["tarel>=0.0.2"]

[project.entry-points."tarel.providers"]
"{name}" = "{module_name}.provider:create_provider"

[tool.hatch.build.targets.wheel]
packages = ["src/{module_name}"]
'''


def _provider_template(name: str) -> str:
    class_name = "".join(part.capitalize() for part in re.split(r"[-_]", name)) + "Provider"
    return f'''"""Candidate {name} provider adapter. Inactive until reviewed and installed."""

from tarel.providers.contracts import ProviderFailure, StructuredRequest


class {class_name}:
    def __init__(self, name: str, config: dict[str, object], timeout: float) -> None:
        self.name = name
        self.default_model = str(config.get("model") or "") or None
        self.config = config
        self.timeout = timeout

    def generate_structured(self, request: StructuredRequest) -> dict[str, object]:
        raise ProviderFailure(
            "not_implemented",
            "Implement one bounded structured-generation request and response parser.",
        )


def create_provider(*, name: str, config: dict[str, object], timeout: float) -> {class_name}:
    return {class_name}(name, config, timeout)
'''


def _task_template(name: str) -> str:
    return f"""# TAREL Provider Task: {name}

Implement a provider adapter for TAREL's `StructuredProvider` contract.

## Boundaries

- Keep credentials only in the private provider profile or the vendor's standard secret store.
- Send only the messages, schema, model override, token bound, temperature, and reasoning hint
  required by `StructuredRequest`.
- Return a JSON object or a precise `ProviderFailure`; never silently repair semantic output.
- Use the vendor's native JSON-schema or forced-tool mechanism when available.
- Keep network dependencies optional; prefer the standard library for a simple HTTP protocol.
- Do not edit TAREL kernel contracts to accommodate this adapter.
- Do not install the candidate until a human has reviewed its code and data boundary.

## Research and verification

- Use official API documentation and record concise links in `references/protocol.md`.
- Test redaction, authentication failure, timeout, invalid output, and one valid structured result.
- Verify exactly which request fields and source data leave the machine.

## Activation

After review, install this package and configure a private profile whose `adapter` is `{name}`.
The entry point is discovered only from installed Python package metadata.
"""


def _readme_template(name: str) -> str:
    return f"""# {name} provider candidate

Generated by `tarel provider scaffold {name}`. This directory is inactive until it is reviewed,
installed, and referenced by a private provider profile. Start with `PROVIDER_TASK.md`.
"""


def _protocol_reference_template(name: str) -> str:
    return f"""# {name} protocol evidence

## Official sources

- Add official API and authentication links here.

## Structured output

- Document JSON-schema or forced-tool behavior and verified limitations.

## Privacy boundary

- Document the endpoint, retention assumptions, and which request fields leave TAREL.

## Error mapping

- Document authentication, rate-limit, timeout, and invalid-response behavior.
"""
